version: '2'
services:
  db:
    image: postgres
    ports:
    - "5432"
  app:
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000"
    depends_on:
      - db
  nginx:
    image: nginx
    volumes_from:
      - app
    depends_on:
      - app
